from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("articles", "0002_savedarticle")]
    operations = [
        migrations.CreateModel(name="SourceRegistry", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("source", models.CharField(max_length=160, unique=True)), ("domain", models.CharField(blank=True, max_length=255)), ("source_type", models.CharField(choices=[("official", "Official"), ("reputable_news", "Highly reputable news"), ("reference", "Reference"), ("general_news", "Reputable general news"), ("web", "General web")], default="web", max_length=32)), ("trust_tier", models.PositiveSmallIntegerField(default=5)), ("priority", models.PositiveSmallIntegerField(default=5)), ("active", models.BooleanField(default=True))]),
        migrations.CreateModel(name="ArticleMetadata", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("quality_score", models.FloatField(default=0.0)), ("freshness_score", models.FloatField(default=0.0)), ("source_trust", models.FloatField(default=0.0)), ("verification_status", models.CharField(default="UNVERIFIED", max_length=32)), ("retrieved_at", models.DateTimeField(auto_now=True)), ("article", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="active_metadata", to="articles.article"))]),
        migrations.CreateModel(name="Claim", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("text", models.TextField()), ("status", models.CharField(choices=[("SUPPORTED", "Supported"), ("CONTRADICTED", "Contradicted"), ("MIXED", "Mixed"), ("INSUFFICIENT_EVIDENCE", "Insufficient evidence")], default="INSUFFICIENT_EVIDENCE", max_length=32)), ("created_at", models.DateTimeField(auto_now_add=True)), ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="claims", to="articles.article"))]),
        migrations.CreateModel(name="ProcessingRecord", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("stage", models.CharField(max_length=64)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("article", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="processing_records", to="articles.article"))]),
        migrations.CreateModel(name="ClaimEvidence", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("source", models.CharField(max_length=255)), ("title", models.TextField()), ("url", models.URLField(max_length=1000)), ("excerpt", models.TextField(blank=True)), ("stance", models.CharField(choices=[("supports", "Supports"), ("contradicts", "Contradicts")], max_length=16)), ("retrieved_at", models.DateTimeField(auto_now_add=True)), ("claim", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence", to="articles.claim"))]),
    ]
