import { Link, useParams } from 'react-router-dom'
import type { ReactNode } from 'react'
import { ArticleGrid } from '../components/ArticleGrid'
import { CategoryBadge } from '../components/CategoryBadge'
import { EmptyState } from '../components/EmptyState'
import { ErrorState } from '../components/ErrorState'
import { SaveButton } from '../components/SaveButton'
import { Skeleton } from '../components/Skeleton'
import { useArticle, useRelatedArticles, useTimeline } from '../hooks/useArticles'
import { formatDate } from '../utils/formatDate'

function Insight({ title, children }: { title:string; children: ReactNode }) { if (!children) return null; return <section className="rounded-xl border bg-white p-5"><h2 className="font-bold text-slate-900">{title}</h2><div className="mt-2 whitespace-pre-line leading-7 text-slate-700">{children}</div></section> }
export function ArticleDetailPage() { const id=Number(useParams().id); const article=useArticle(id); const related=useRelatedArticles(id); const timeline=useTimeline(id); if(article.isLoading) return <div className="space-y-4"><Skeleton className="h-8 w-3/4"/><Skeleton className="h-5 w-1/3"/><Skeleton className="h-60 w-full"/></div>; if(article.isError || !article.data) return <ErrorState error={article.error} onRetry={()=>article.refetch()}/>; const a=article.data; return <article className="mx-auto max-w-4xl"><div className="flex flex-wrap items-center justify-between gap-3"><CategoryBadge label={a.category}/><div className="flex gap-2"><SaveButton articleId={a.id}/><Link to={`/article/${a.id}/chat`} className="rounded-md bg-brand-600 px-3 py-2 text-sm font-medium text-white hover:bg-brand-700">Ask about this</Link></div></div><h1 className="mt-5 text-3xl font-bold tracking-tight sm:text-4xl">{a.title}</h1><p className="mt-3 text-sm text-slate-500">{a.source || 'Unknown source'} · {formatDate(a.published_at)}</p>{a.summary&&<p className="mt-6 text-xl leading-8 text-slate-700">{a.summary}</p>}<div className="mt-7 space-y-4"><Insight title="Background">{a.background}</Insight><Insight title="Why it matters">{a.importance}</Insight><Insight title="Potential impact">{a.expected_impact}</Insight>{a.content&&<Insight title="Article">{a.content}</Insight>}</div><section className="mt-8"><h2 className="text-xl font-bold">Timeline</h2>{timeline.isError?<div className="mt-3"><ErrorState error={timeline.error} onRetry={()=>timeline.refetch()}/></div>:timeline.isLoading?<Skeleton className="mt-3 h-28 w-full"/>:timeline.data?.events.length?<div className="mt-3 space-y-3 border-l-2 border-brand-200 pl-5">{timeline.data.events.map(event=><a key={event.id} href={event.url} target="_blank" rel="noreferrer" className="block"><p className="font-medium text-brand-700">{event.title}</p><p className="text-sm text-slate-500">{event.source} · {formatDate(event.published_at)}</p></a>)}</div>:<p className="mt-2 text-slate-500">{timeline.data?.narrative || 'No timeline is available yet.'}</p>}</section><section className="mt-9"><h2 className="mb-4 text-xl font-bold">Related news</h2>{related.isError?<ErrorState error={related.error} onRetry={()=>related.refetch()}/>:related.data?.results.length?<ArticleGrid articles={related.data.results}/>:<EmptyState title="No related stories yet"/>}</section><section className="mt-9 rounded-xl border bg-slate-50 p-5"><h2 className="font-bold">Source</h2><p className="mt-2 text-sm text-slate-600">Originally published by {a.source || 'the source'}.</p><a href={a.url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-medium text-brand-700 hover:underline">Read the full story ↗</a></section></article> }
