import { useSearchParams } from 'react-router-dom'
import { ArticleGrid } from '../components/ArticleGrid'
import { EmptyState } from '../components/EmptyState'
import { ErrorState } from '../components/ErrorState'
import { Pagination } from '../components/Pagination'
import { useArticles } from '../hooks/useArticles'
import { useCategories } from '../hooks/useCategories'
import { useSources } from '../hooks/useSources'

export function LibraryPage() {
 const [params, setParams] = useSearchParams(); const page = Number(params.get('page') || 1); const filters = { category: params.get('category') || undefined, source: params.get('source') || undefined, date_from: params.get('date_from') || undefined, date_to: params.get('date_to') || undefined, page }; const articles = useArticles(filters); const categories = useCategories(); const sources = useSources(); const set = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); next.delete('page'); setParams(next) }; const setPage = (value:number) => { const n = new URLSearchParams(params); n.set('page', String(value)); setParams(n) };
 return <div><h1 className="text-3xl font-bold">News Library</h1><p className="mt-2 text-slate-600">Explore persisted articles without loading the whole archive.</p><div className="mt-6 grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm">Category<select value={filters.category || ''} onChange={e=>set('category', e.target.value)} className="mt-1 w-full rounded-md border p-2"><option value="">All categories</option>{categories.data?.map(x=><option key={x.key} value={x.key}>{x.title}</option>)}</select></label><label className="text-sm">Source<select value={filters.source || ''} onChange={e=>set('source', e.target.value)} className="mt-1 w-full rounded-md border p-2"><option value="">All sources</option>{sources.data?.map(x=><option key={x.source} value={x.source}>{x.source} ({x.count})</option>)}</select></label><label className="text-sm">From<input type="date" value={filters.date_from || ''} onChange={e=>set('date_from',e.target.value)} className="mt-1 w-full rounded-md border p-2" /></label><label className="text-sm">To<input type="date" value={filters.date_to || ''} onChange={e=>set('date_to',e.target.value)} className="mt-1 w-full rounded-md border p-2" /></label></div><div className="mt-6">{articles.isError ? <ErrorState error={articles.error} onRetry={()=>articles.refetch()} /> : articles.data?.results.length === 0 ? <EmptyState title="No matching articles" description="Adjust the filters and try again." /> : <ArticleGrid articles={articles.data?.results} loading={articles.isLoading} />}{articles.data && <Pagination page={page} hasNext={Boolean(articles.data.next)} hasPrevious={Boolean(articles.data.previous)} count={articles.data.count} onPageChange={setPage}/>}</div></div>
}
